# Generated by Django 3.2.25 on 2024-06-17 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Título do Anúncio', max_length=255)),
                ('preco', models.FloatField()),
                ('foto_url', models.CharField(default='null', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('Novo', 'Novo'), ('Semi-novo', 'Semi-novo'), ('Usado', 'Usado')], default='Novo', max_length=10)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=255)),
                ('foto_url', models.CharField(default='null', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('utilizador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_started', to=settings.AUTH_USER_MODEL)),
                ('utilizador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_participating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id_localizacao', models.AutoField(primary_key=True, serialize=False)),
                ('localizacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoAlugado',
            fields=[
                ('id_produto_alugado', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtoalugado', to='index.anuncio')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id_mensagem', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.chat')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.anuncio')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.categoria'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.localizacao'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
