# Generated by Django 3.2.25 on 2024-06-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='data',
        ),
    ]
