# Generated by Django 3.2.25 on 2024-06-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto_url',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
