# Generated by Django 3.2.25 on 2024-06-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_mensagem_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoalugado',
            name='preco_total',
            field=models.FloatField(default=0.0),
        ),
    ]
