# Generated by Django 3.2.25 on 2024-06-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_localizacao_utilizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('preco', models.FloatField()),
                ('ativo', models.BooleanField()),
                ('estado', models.CharField(choices=[('N', 'Novo'), ('SN', 'Semi-novo'), ('U', 'Usado')], max_length=2)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.categoria')),
                ('id_localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.localizacao')),
                ('id_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.utilizador')),
            ],
        ),
    ]
