# Generated by Django 3.2.25 on 2024-06-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_produtoalugado_preco_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoalugado',
            name='preco_total',
        ),
    ]
