# Generated by Django 3.2.25 on 2024-06-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_anuncio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='id_localizacao',
            new_name='localizacao',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='id_utilizador',
            new_name='utilizador',
        ),
    ]
