# Generated by Django 3.2.25 on 2024-06-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20240614_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='foto_url',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='foto_url',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
