# Generated by Django 3.2.25 on 2024-06-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20240614_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Semi-novo', 'Semi-novo'), ('Usado', 'Usado')], max_length=10),
        ),
    ]
