# Generated by Django 3.2.25 on 2024-06-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_anuncio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='descricao',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
