# Generated by Django 3.2.25 on 2024-06-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_anuncio_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.TextField(default='null'),
        ),
    ]
