# Generated by Django 3.2.25 on 2024-06-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_anuncio_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.anuncio')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.utilizador')),
            ],
        ),
    ]
