# Generated by Django 3.2.25 on 2024-06-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('utilizador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_started', to='index.utilizador')),
                ('utilizador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_participating', to='index.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoAlugado',
            fields=[
                ('id_produto_alugado', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('preco_total', models.FloatField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.anuncio')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id_mensagem', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.chat')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.utilizador')),
            ],
        ),
    ]
