# Generated by Django 3.2.25 on 2024-06-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_chat_mensagem_produtoalugado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoalugado',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtoalugado', to='index.anuncio'),
        ),
    ]
